# Generated by Django 5.0.6 on 2024-05-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='targeted_item_cost',
            field=models.IntegerField(default=0),
        ),
    ]
